termx:
  url: 'https://termx.kodality.dev/api/'
keycloak:
  sso-url:
  client-id:
  client-secret:
import:
  class: 'pub.etervis.classification-import'
  status: 'draft'
  language: 'et'
  cs:
    dryRun: true
    cleanVersion: true
    replaceConcept: true
  vs:
    dryRun: true


