termx:
  url: 'https://termx.kodality.dev/api/'
  #url: 'http://localhost:8200/'
keycloak:
  sso-url:
  client-id:
  client-secret:
  token:
import:
  class: 'pub.etervis.classification-import'
  space: 'ee-base'
  space-package: 'test'
  status: 'draft'
  language: 'et'
  cs:
    dryRun: true
    cleanVersion: true
    replaceConcept: true
  vs:
    dryRun: true


